.PHONY: clean All

All:
	@echo "----------Building project:[ RayBoxGUI - Debug ]----------"
	@cd "RayBoxGUI" && "$(MAKE)" -f  "RayBoxGUI.mk"
clean:
	@echo "----------Cleaning project:[ RayBoxGUI - Debug ]----------"
	@cd "RayBoxGUI" && "$(MAKE)" -f  "RayBoxGUI.mk" clean
